name: Test container stuff

on:
  push:

  workflow_dispatch:
    inputs:
      vers_info:
        description: 'Version for file name'
        required: true
        default: ''

jobs:
  gather-info:
    runs-on: ubuntu-latest
    outputs:
      commitish: ${{ steps.set_output.outputs.commitish_value }}

    steps:
    - name: Get Short SHA
      if: ${{ github.event_name != 'workflow_dispatch' }}
      id: get_short_sha
      run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Get Dispatch Input
      if: ${{ github.event_name == 'workflow_dispatch' }}
      id: get_dispatch_input
      run: echo "DISP_INPUT=${{ github.event.inputs.vers_info }}" >> $GITHUB_ENV

    - name: Get Tag Name
      if: startswith( github.ref, 'refs/tags/')
      id: get_tag_name
      run: echo "TAG_NAME=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

    - name: Set Job Output
      id: set_output
      run: |
        if [[ -v DISP_INPUT ]]; then
          echo "commitish_value=$DISP_INPUT" >> "$GITHUB_OUTPUT"
        elif [[ -v TAG_NAME ]]; then
          echo "commitish_value=$TAG_NAME" >> "$GITHUB_OUTPUT"
        else
          echo "commitish_value=$SHORT_SHA" >> "$GITHUB_OUTPUT"
        fi

  make-appimage:  
    name: Make AppImage
    runs-on: ubuntu-latest
    needs: gather-info

    container:
      image: ubuntu:22.04
      options: --privileged
      volumes:
        - ${{ github.workspace }}:/reporoot
      env:
        COMMITISH: ${{ needs.gather-info.outputs.commitish }}"
      
    steps:
      - run: | 
          apt-add-repository ppa:git-core/ppa
          apt-get update
          apt-get install -y git

      - uses: actions/checkout@v4
      - run: echo "Commitish is $COMMITISH"
